#!/bin/bash

DOCKER_COMPOSE_FILE="./docker-compose.yml"
PROMETHEUS_TEMPLATE="monitoring/prometheus/prometheus_template.yml"
PROMETHEUS_CONFIG="monitoring/prometheus/prometheus.yml"

if [[ ! -f "$DOCKER_COMPOSE_FILE" ]]; then
    echo "Erreur: Le fichier $DOCKER_COMPOSE_FILE n'existe pas."
    exit 1
fi

if [[ ! -f "$PROMETHEUS_TEMPLATE" ]]; then
    echo "Erreur: Le fichier $PROMETHEUS_TEMPLATE n'existe pas."
    exit 1
fi

# grep et sed pour extraire les container_name
CONTAINERS=$(grep -E '^\s*container_name:\s*' "$DOCKER_COMPOSE_FILE" | sed 's/.*container_name:\s*//' | sed 's/["\x27]//g' | tr -d ' ')

cp "$PROMETHEUS_TEMPLATE" "monitoring/prometheus/prometheus.yml"

echo "" >> "$PROMETHEUS_CONFIG"

while IFS= read -r container; do
    
    if grep -q "job_name: $container" "$PROMETHEUS_CONFIG"; then
        continue
    fi
    
    cat >> "$PROMETHEUS_CONFIG" << EOF

- job_name: $container
  honor_timestamps: true
  static_configs:
    - targets:
        - $container:9100
EOF

done <<< "$CONTAINERS"
